name: Check metadata

on: [push, pull_request]

jobs:
  ubuntu:
    name: Check meta data
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Check svg
        run: ./scripts/check_svg_meta.sh
