name: Check metadata

on: [push, pull_request]

jobs:
  ubuntu:
    name: Check meta data
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup
        run: |
          sudo wget https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -O /usr/bin/yq
          sudo chmod +x /usr/bin/yq
      - name: Check svg
        run: ./scripts/check_svg_meta.sh
